% EEGLAB history file generated on the 23-Sep-2019
% ------------------------------------------------
[ALLEEG EEG CURRENTSET ALLCOM] = eeglab;
[STUDY ALLEEG] = std_editset( STUDY, [], 'name','trigger1_1016_bluff','task','poker',...
'commands',{{'index' 1 'load' '/Volumes/colin/conditionsEEG/10b_condition1_triggerId.set'}...    
{'index' 2 'load' '/Volumes/colin/conditionsEEG/10b_condition2_triggerId.set'} ...
{'index' 3 'load' '/Volumes/colin/conditionsEEG/11b_condition1_triggerId.set'}...
{'index' 4 'load' '/Volumes/colin/conditionsEEG/11b_condition2_triggerId.set'}... 
{'index' 5 'load' '/Volumes/colin/conditionsEEG/12b_condition1_triggerId.set'} ...
{'index' 6 'load' '/Volumes/colin/conditionsEEG/12b_condition2_triggerId.set'}...
{'index' 7 'load' '/Volumes/colin/conditionsEEG/13b_condition1_triggerId.set'} ...
{'index' 8 'load' '/Volumes/colin/conditionsEEG/13b_condition2_triggerId.set'}...
{'index' 9 'load' '/Volumes/colin/conditionsEEG/14b_condition1_triggerId.set'}...
{'index' 10 'load' '/Volumes/colin/conditionsEEG/14b_condition2_triggerId.set'} ...
{'index' 11 'load' '/Volumes/colin/conditionsEEG/15b_condition1_triggerId.set'} ...
{'index' 12 'load' '/Volumes/colin/conditionsEEG/15b_condition2_triggerId.set'} ...
{'index' 13 'load' '/Volumes/colin/conditionsEEG/16b_condition1_triggerId.set'}...
{'index' 14 'load' '/Volumes/colin/conditionsEEG/16b_condition2_triggerId.set'},...
{'index' 15 'load' '/Volumes/colin/conditionsEEG/17b_condition2_triggerId.set'}...
{'index' 16 'load' '/Volumes/colin/conditionsEEG/17b_condition1_triggerId.set'},...
{'inbrain' 'on' 'dipselect' 0.15} {'index' 1 'comps' [1:57]} {'index' 2 'comps' [1:57] }...
    {'index' 3 'comps' [1:57] } {'index' 4 'comps' [1:57]} {'index' 5 'comps' [1:57] } {'index' 6 'comps' [1:57]}...
    {'index' 7 'comps' [1:57] } {'index' 8 'comps' [1:57]} {'index' 9 'comps' [1:57] } {'index' 10 'comps' [1:57] }...
    {'index' 11 'comps' [1:57] } {'index' 12 'comps' [1:57]} {'index' 13 'comps' [1:57] } {'index' 14 'comps' [1:57]}...
    {'index' 15 'comps' [1:59] } {'index' 16 'comps' [1:59] }},...
    'updatedat','on','savedat','on','rmclust','on');
[STUDY ALLEEG] = std_checkset(STUDY, ALLEEG);
CURRENTSTUDY = 1; 
EEG = ALLEEG; CURRENTSET = [1:length(EEG)];
EEG = eeg_checkset( EEG );
[STUDY EEG] = pop_savestudy( STUDY, EEG, 'filename','trigger1_study.study','filepath','/Volumes/colin/conditionsEEG');
CURRENTSTUDY = 1; EEG = ALLEEG; CURRENTSET = [1:length(EEG)];

STUDY = pop_statparams(STUDY, 'effect','marginal','groupstats','on','condstats','on','singletrials','on');
eeglab redraw;

